"use client";
import {useEffect,useState} from "react"; import {api,DEV_USER,bootstrapDevUser,authMe} from "../lib/api"; import {supabase} from "../lib/supabase"; import LiveClassroom from "../components/LiveClassroom"; import {MasteryView,RoadmapsView,ProgressView,JournalView} from "../components/RealViews"; import HomeworkUpload from "../components/HomeworkUpload"; import {LearningHome,CurriculumRoadmaps} from "../components/LearningHome"; import IntegrationStatus from "../components/IntegrationStatus";
const nav=["Today","Classroom","College","Roadmaps","Mastery","Progress","Library","Journal"];
const adds=[["External Learning","Log something learned elsewhere"],["Homework","Get help while protecting mastery"],["Learning Resource","Add a video, graph, article or file"],["College Course","Add a semester course"],["Question","Ask the tutor something"]];
export default function Home(){
 const [page,setPage]=useState("Today"),[userId,setUserId]=useState(DEV_USER),[activeCourse,setActiveCourse]=useState<string>(""),[menu,setMenu]=useState(false),[modal,setModal]=useState<string|null>(null),[data,setData]=useState<any>(null),[err,setErr]=useState(""),[toast,setToast]=useState(""),[authReady,setAuthReady]=useState(false);
 async function refresh(uid=userId){if(!uid){setErr("No learner session is active.");return}try{setData(await api.dashboard(uid));setErr("")}catch(e:any){setErr("Backend is not connected yet. "+e.message)}}
 useEffect(()=>{let alive=true;(async()=>{const {data}=await supabase.auth.getSession();if(data.session){try{const u=await authMe();if(alive){setUserId(u.id);await refresh(u.id)}}catch(e:any){if(alive)setErr(e.message)}}else if(DEV_USER){try{const u=await bootstrapDevUser();if(alive){setUserId(u.id);await refresh(u.id)}}catch{}}if(alive)setAuthReady(true)})();const {data:sub}=supabase.auth.onAuthStateChange(async(_event,session)=>{if(session){try{const u=await authMe();if(alive){setUserId(u.id);await refresh(u.id)}}catch(e:any){if(alive)setErr(e.message)}}else if(alive){setUserId("");setData(null)}});return()=>{alive=false;sub.subscription.unsubscribe()}},[]);
 if(!authReady)return <div className="authShell"><div className="authCard"><div className="logo"><span>PERSONAL</span>Learning OS</div><p className="muted">Opening your learning system…</p></div></div>;
 if(!userId&&!DEV_USER)return <Login/>;
 return <div className="shell"><aside className="rail"><div className="logo"><span>PERSONAL</span>Learning OS</div><Nav page={page} setPage={setPage}/></aside><main className="content">
 <header className="header"><div><div className="eyebrow">Your learning system</div><h1>{page}</h1></div><div className="actions"><button className="btn" onClick={()=>supabase.auth.signOut()}>Sign out</button><button className="btn primary" onClick={()=>setMenu(!menu)}>＋ Add</button></div></header>
 {menu&&<div className="menu">{adds.map(([a,b])=><div key={a} onClick={()=>{setModal(a);setMenu(false)}}><b>{a}</b><small>{b}</small></div>)}</div>}
 {page==="Today"&&<Today data={data} err={err} setPage={setPage} setModal={setModal} setActiveCourse={setActiveCourse} userId={userId}/>}
 {page==="Classroom"&&userId&&<LiveClassroom userId={userId} courseId={activeCourse||undefined}/>}{page==="College"&&<College data={data} setModal={setModal}/>}
 {page==="Roadmaps"&&userId&&<CurriculumRoadmaps userId={userId} onOpen={(id)=>{setActiveCourse(id);setPage("Classroom")}}/>}
 {page==="Mastery"&&userId&&<MasteryView userId={userId}/>}
 {page==="Progress"&&userId&&<ProgressView userId={userId}/>}
 {page==="Library"&&<Library data={data} setModal={setModal}/>}
 {page==="Journal"&&userId&&<JournalView userId={userId}/>}
 {modal&&<Modal userId={userId} kind={modal} close={()=>setModal(null)} saved={()=>{setToast("Saved");setModal(null);refresh();setTimeout(()=>setToast(""),1800)}}/>}
 {toast&&<div className="toast">{toast}</div>}</main>
 <div className="mobileNav">{["Today","Classroom","College","Mastery","Journal"].map(x=><button key={x} className={page===x?"on":""} onClick={()=>setPage(x)}>{x}</button>)}</div></div>
}
function Login(){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");async function signIn(){setBusy(true);setMsg("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message);setBusy(false)}async function signUp(){setBusy(true);setMsg("");const {error}=await supabase.auth.signUp({email,password});setMsg(error?error.message:"Check your email to confirm your account, then return here to sign in.");setBusy(false)}return <div className="authShell"><div className="authCard"><div className="logo"><span>PERSONAL</span>Learning OS</div><h1>Welcome back</h1><p className="muted">Sign in to your private learning system.</p><div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></div><div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></div>{msg&&<p className="muted">{msg}</p>}<div className="actions"><button className="btn primary" disabled={busy||!email||!password} onClick={signIn}>{busy?"Please wait…":"Sign in"}</button><button className="btn" disabled={busy||!email||password.length<8} onClick={signUp}>Create my account</button></div></div></div>}
function Nav({page,setPage}:any){return <nav className="nav">{nav.map(x=><button key={x} className={page===x?"on":""} onClick={()=>setPage(x)}>{x}</button>)}</nav>}
function Today({data,err,setPage,setModal,setActiveCourse,userId}:any){let ext=data?.external_learning_pending||[], courses=data?.college_courses||[], hw=data?.assignments||[];return <>
 <section className="hero"><div><span className="badge">NEXT BEST ACTION</span><h2>Start with your Daily Gate.</h2><p className="muted">Retrieve what you learned before adding something new. The tutor will repair gaps instead of letting them pile up.</p></div><button className="btn primary" onClick={()=>setPage("Classroom")}>Start learning →</button></section>
 {err&&<div className="card" style={{marginTop:14}}><b>Development connection</b><p className="muted">{err}</p></div>}
 <div style={{marginTop:14}}><IntegrationStatus/></div><h2 className="section">Needs your attention</h2><div className="grid two">
  <div className="card"><div className="eyebrow">External learning</div><h3>{ext.length} waiting for proof</h3>{ext.slice(0,3).map((x:any)=><div className="row" key={x.id}><span><b>{x.topic}</b><br/><small className="muted">{x.source}</small></span><span className="status warn">PROVE</span></div>)}{!ext.length&&<p className="muted">Nothing waiting. Log learning from Zero to Mastery, class, books or videos when you have it.</p>}<button className="btn" onClick={()=>setModal("External Learning")}>Log external learning</button></div>
  <div className="card"><div className="eyebrow">College</div><h3>{hw.length} active assignments</h3>{hw.slice(0,3).map((x:any)=><div className="row" key={x.id}><span>{x.title}</span><span className="status">{x.status?.replaceAll("_"," ")}</span></div>)}{!hw.length&&<p className="muted">No active homework in the database.</p>}<button className="btn" onClick={()=>setModal("Homework")}>Add homework</button></div>
 </div><h2 className="section">Your active learning</h2>{userId&&<LearningHome userId={userId} onOpen={(id)=>{setActiveCourse(id);setPage("Classroom")}}/>}</>}
function Classroom(){return <div className="classroom" style={{marginTop:22}}><div className="card teacher"><div className="eyebrow">DAILY GATE</div><h2>Show me what you remember.</h2><div className="prompt"><b>AI Teacher</b><p>Teach yesterday's key idea back to me without looking it up. I’ll ask a fresh application question afterward.</p></div><textarea className="answer" placeholder="Explain it in your own words…"/><div className="actions"><button className="btn primary">Submit</button><button className="btn">Hint</button></div><div className="soft" style={{marginTop:16}}><div className="eyebrow">HELP LADDER</div><p className="muted">The tutor escalates from Socratic questions to a full explanation only when needed. Assistance is recorded.</p></div></div><div className="grid"><div className="card"><div className="eyebrow">VISUAL</div><h3>Concept view</h3><div className="visual"><b>Visuals appear when they clarify the idea.</b><p className="muted">Graphs, diagrams, code traces and interactive models support the lesson without replacing your own reasoning.</p></div></div><div className="card"><div className="eyebrow">VIDEO REFERENCE</div><h3>Optional demonstration</h3><p className="muted">Watching records exposure only. You still prove the concept afterward.</p></div></div></div>}
function College({data,setModal}:any){let c=data?.college_courses||[],a=data?.assignments||[];return <><div className="grid two" style={{marginTop:22}}>{c.map((x:any)=><div className="card" key={x.id}><div className="eyebrow">COLLEGE COURSE</div><h3>{x.code}</h3><p>{x.title}</p><small className="muted">{x.term||"Current term"}</small></div>)}<div className="card"><h3>Add your semester</h3><p className="muted">Syllabus, assignments, review sheets and course mastery can live together.</p><button className="btn primary" onClick={()=>setModal("College Course")}>Add course</button></div></div><h2 className="section">Assignments</h2><div className="card">{a.map((x:any)=><div className="row" key={x.id}><span>{x.title}</span><b>{x.status}</b></div>)}{!a.length&&<div className="empty">No assignments yet.</div>}</div></>}
function Library({data,setModal}:any){return <div className="card" style={{marginTop:22}}><h2>Learning Library</h2><p className="muted">Keep course materials and useful visual references organized by concept. Viewing a resource never counts as mastery.</p><button className="btn primary" onClick={()=>setModal("Learning Resource")}>Add resource</button></div>}
function Simple({title,text}:any){return <div className="card" style={{marginTop:22}}><h2>{title}</h2><p className="muted">{text}</p></div>}
function Modal({userId,kind,close,saved}:any){const [f,setF]=useState<any>({});const [busy,setBusy]=useState(false),[error,setError]=useState("");function field(k:string,v:string){setF({...f,[k]:v})}async function go(){if(!userId){setError("Development user is not configured.");return}setBusy(true);try{if(kind==="External Learning")await api.external(userId,{source:f.source||"",topic:f.topic||"",covered:f.covered||"",minutes:f.minutes?Number(f.minutes):null});else if(kind==="College Course")await api.course(userId,{code:f.code||"",title:f.title||"",term:f.term||null});else if(kind==="Homework")await api.homework(userId,{title:f.title||"",notes:f.notes||"",college_course_id:f.course||null});else if(kind==="Learning Resource")await api.resource(userId,{title:f.title||"",resource_type:f.type||"video",url:f.url||null,concept_ids:[],metadata_json:{}});else await api.note(userId,{body:f.notes||f.question||"",course_id:null,lesson_id:null,concept_id:null});saved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <div className="overlay" onMouseDown={e=>e.currentTarget===e.target&&close()}><div className="modal"><div className="eyebrow">ADD TO LEARNING OS</div><h2>{kind}</h2>{kind==="External Learning"?<><F label="Source" ph="Zero to Mastery" v={(x:string)=>field("source",x)}/><F label="Topic" ph="Python functions" v={(x:string)=>field("topic",x)}/><F label="What did you cover?" area v={(x:string)=>field("covered",x)}/><F label="Minutes (optional)" ph="55" v={(x:string)=>field("minutes",x)}/><div className="soft"><b>Next: prove it.</b><p className="muted">Saving this records exposure. It will appear on Today until you demonstrate the knowledge.</p></div></>:kind==="College Course"?<><F label="Course code" ph="MA440" v={(x:string)=>field("code",x)}/><F label="Course title" ph="Precalculus" v={(x:string)=>field("title",x)}/><F label="Term" ph="Fall 2026" v={(x:string)=>field("term",x)}/></>:kind==="Homework"?<><F label="Assignment title" ph="Homework 6 — Logarithms" v={(x:string)=>field("title",x)}/><F label="Notes / questions" area v={(x:string)=>field("notes",x)}/><div className="soft"><b>Analyze → Diagnose → Attempt → Hint → Fresh Check</b><p className="muted">Homework completion stays separate from mastery.</p></div>{userId&&<HomeworkUpload userId={userId}/>}</>:kind==="Learning Resource"?<><F label="Title" ph="Function transformations video" v={(x:string)=>field("title",x)}/><F label="URL" ph="https://…" v={(x:string)=>field("url",x)}/></>:<F label="Question / note" area v={(x:string)=>field("question",x)}/>} {error&&<p className="warn">{error}</p>}<div className="actions"><button className="btn primary" disabled={busy} onClick={go}>{busy?"Saving…":"Save"}</button><button className="btn" onClick={close}>Cancel</button></div></div></div>}
function F({label,ph="",area=false,v}:any){return <div className="field"><label>{label}</label>{area?<textarea rows={4} placeholder={ph} onChange={e=>v(e.target.value)}/>:<input placeholder={ph} onChange={e=>v(e.target.value)}/>}</div>}
